version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_KEEP_ALIVE=5m
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -sf http://localhost:11434/api/tags >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 15
      start_period: 10s
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "5678:5678"
    environment:
      # Basic Auth (ändere in .env)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASS}
      # Zeitzone (optional)
      - TZ=Europe/Zurich
      # Optional: Public URL falls Reverse Proxy
      # - N8N_HOST=n8n.local
      # - N8N_PROTOCOL=https
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  ollama_data:
  n8n_data:
