version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_REST_DISABLED=false
      - N8N_PUBLIC_API_DISABLED=false
      - N8N_PUBLIC_API_REST_DISABLED=false
      - N8N_AUTH_DISABLED=true
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  ollama_data:
  n8n_data:
